### ISSUE TITLE
print doesn't make newlines properly while this is active.

### ISSUE THREAD

**Issue by Xenthio** [a11ce/defKey#1]
after defKey.start() is run, print no longer creates newlines properly, instead of a new line, it kinda does this weird drop thing... 
![image](https://user-images.githubusercontent.com/28588188/80170192-c7f9b280-862a-11ea-909c-fcd9cc547ef7.png)

**Comment by a11ce** [comment]
Adding `\r` (carriage return) at the end of print statements fixes this temporarily, but I'll look into something better. I suspect it has to do with changing the mode of stdin within the getch function.

Compare:
```
from defKey import defKey
defKey.start()
print("one\r")
print("two\r")
defKey.stop()
``` 

and 
```
from defKey import defKey
defKey.start()
print("one")
print("two")
defKey.stop()
```

**Comment by Xenthio** [comment]
already found that fix and that fixed it! thanks for the reply though!! you might still wanna look into why it breaks the terminal. instead of this kinda 'cheaty' fix.

**Comment by a11ce** [comment]
Seems like the defKey thread is just eating a carriage return, so adding an extra one is the cleanest fix. Are there any other issues?

If you don't want to type the `\r` each time, you can redefine/decorate `print()` to automatically add it. If a missing carriage return is the only issue, this could be added to the library itself.

**Comment by Xenthio** [comment]
I'll also report another issue with this.
